language: python
python:
- '2.7'
install: pip install -r requirements/dev.txt --allow-external twill --allow-unverified
  twill
script: nosetests
env:
  global:
  - secure: axjczn/ffkZWCRv9B3FOkad2S6PZHisOvv+uTpZ9pf5+Cq7mU0XHJGWTC/PiBABoTXTebvTp6zzBjFowPO0Ach1zeVXoyCmnL+WD6slw5IMtzrEEldjUNPUWTzIjtmRQzYIIJthLCzBN7Z0LIHAGAg682RbQfdu8WODXcvXOrZU=
