"""Added scheduled_time and next_fire to Post

Revision ID: 17c4355c76cc
Revises: 18fcaf0982e4
Create Date: 2014-02-17 19:35:24.391000

"""

# revision identifiers, used by Alembic.
revision = '17c4355c76cc'
down_revision = '18fcaf0982e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('scheduled_time', sa.Time))
    op.add_column('posts', sa.Column('next_fire', sa.DateTime))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_columm('posts', 'scheduled_time')
    op.drop_columm('posts', 'next_fire')
    ### end Alembic commands ###
