"""Added relationship between user and posts, and user id

Revision ID: 49046c887a42
Revises: 4c4ffd33e4a3
Create Date: 2014-02-13 19:58:30.591000

"""

# revision identifiers, used by Alembic.
revision = '49046c887a42'
down_revision = '4c4ffd33e4a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'user_id')
    ### end Alembic commands ###
