"""Added id to User

Revision ID: a035c108cdc
Revises: 49046c887a42
Create Date: 2014-02-13 20:01:56.532000

"""

# revision identifiers, used by Alembic.
revision = 'a035c108cdc'
down_revision = '49046c887a42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
